# Generated by Django 5.0.3 on 2024-05-21 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link', models.URLField()),
                ('country', models.CharField(max_length=25)),
                ('owner', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('allowedSpeed', models.IntegerField()),
                ('color', models.CharField(max_length=24)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('yearEstablished', models.DateTimeField()),
                ('oldTimerFixes', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='images/')),
                ('carInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_app.automobiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_app.workshop')),
            ],
        ),
    ]
